# swagger_petstore
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SwaggerPetstore
  # Order Status
  class Status1Enum
    STATUS1_ENUM = [
      # TODO: Write general description for PLACED
      PLACED = 'placed'.freeze,

      # TODO: Write general description for APPROVED
      APPROVED = 'approved'.freeze,

      # TODO: Write general description for DELIVERED
      DELIVERED = 'delivered'.freeze
    ].freeze
  end
end
