# swagger_petstore
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SwaggerPetstore
  # Http response received.
  class HttpResponse < CoreLibrary::HttpResponse
  end
end
