# swagger_petstore
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SwaggerPetstore
  # API utility class
  class APIHelper < CoreLibrary::ApiHelper
  end
end
